import { StudentProfile } from "./DiscoverDeck";

export const TWENTY_STUDENT_PROFILES: StudentProfile[] = [
  // 1. FEMALE - STRAIGHT (UoN)
  {
    id: "sp-1",
    name: "Amani Wanjiru",
    age: 21,
    gender: "Female",
    orientation: "Straight",
    campus: "University of Nairobi",
    course: "Medicine & Surgery",
    yearOfStudy: "4th Year",
    distanceKm: 2,
    compatibilityScore: 97,
    verified: true,
    online: true,
    intentMode: "Dating",
    photos: [
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&auto=format&fit=crop&q=80",
    ],
    bio: "Med student at UoN Chiromo campus! Passionate about public health, debate, and exploring Nairobi cafes on weekends.",
    interests: ["Medicine", "Debating", "Coffee & Cafes", "Volunteering"],
    prompts: [{ question: "Key to my heart...", answer: "Good conversation over Kenya AA coffee." }],
    height: "170 cm",
    lifestyle: { smoking: "Non-smoker", drinking: "Social drinker", pets: "Cat lover", religion: "Christian" },
  },

  // 2. FEMALE - LESBIAN (Strathmore)
  {
    id: "sp-2",
    name: "Nia Kamau",
    age: 22,
    gender: "Female",
    orientation: "Lesbian",
    campus: "Strathmore University",
    course: "Financial Economics",
    yearOfStudy: "3rd Year",
    distanceKm: 4,
    compatibilityScore: 94,
    verified: true,
    online: true,
    intentMode: "Dating",
    photos: [
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&auto=format&fit=crop&q=80",
    ],
    bio: "Finance major & amateur bass player. Looking for a genuine girl to share concerts, coffee, and late night study sessions with!",
    interests: ["Live Music & Concerts", "Indie Rock", "Crypto & Web3", "Philosophy"],
    prompts: [{ question: "My ideal Sunday...", answer: "Vinyl records and sunset at Uhuru Park." }],
    height: "168 cm",
    lifestyle: { smoking: "Non-smoker", drinking: "Social drinker", pets: "Dog lover", religion: "Spiritual" },
  },

  // 3. MALE - STRAIGHT (JKUAT)
  {
    id: "sp-3",
    name: "Brian Omondi",
    age: 22,
    gender: "Male",
    orientation: "Straight",
    campus: "Jomo Kenyatta University of Agriculture and Technology",
    course: "Software Engineering",
    yearOfStudy: "4th Year",
    distanceKm: 6,
    compatibilityScore: 95,
    verified: true,
    online: true,
    intentMode: "Dating",
    photos: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80",
    ],
    bio: "Full-stack dev at Juja campus! Love hackathons, basketball, and weekend road trips to Naivasha.",
    interests: ["AI & Coding", "Basketball", "Hackathons", "Travel & Backpacking"],
    prompts: [{ question: "Catch me at...", answer: "The engineering lab building AI apps." }],
    height: "184 cm",
    lifestyle: { smoking: "Non-smoker", drinking: "Social drinker", pets: "No pets", religion: "Christian" },
  },

  // 4. MALE - GAY (UoN)
  {
    id: "sp-4",
    name: "David Kimani",
    age: 21,
    gender: "Male",
    orientation: "Gay",
    campus: "University of Nairobi",
    course: "Architecture & Design",
    yearOfStudy: "3rd Year",
    distanceKm: 3,
    compatibilityScore: 92,
    verified: true,
    online: true,
    intentMode: "Dating",
    photos: [
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800&auto=format&fit=crop&q=80",
    ],
    bio: "Architecture major passionate about modern urban design, art galleries, and acoustic guitar. Looking for a genuine guy on campus!",
    interests: ["Photography", "Philosophy", "Indie Rock", "Coffee & Cafes"],
    prompts: [{ question: "Two truths and a lie...", answer: "I designed a eco-house, I speak French, I dislike coffee." }],
    height: "180 cm",
    lifestyle: { smoking: "Non-smoker", drinking: "Social drinker", pets: "Cat lover", religion: "Agnostic" },
  },

  // 5. FEMALE - STRAIGHT (MMUST)
  {
    id: "sp-5",
    name: "Stacy Muthoni",
    age: 20,
    gender: "Female",
    orientation: "Straight",
    campus: "Masinde Muliro University of Science and Technology",
    course: "Disaster Management & Nursing",
    yearOfStudy: "2nd Year",
    distanceKm: 7,
    compatibilityScore: 91,
    verified: true,
    online: true,
    intentMode: "Dating",
    photos: [
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80",
    ],
    bio: "MMUST Kakamega campus student! Passionate about healthcare volunteering, hiking, and baking pastries.",
    interests: ["Volunteering", "Baking & Cooking", "Gym & Fitness", "Podcasts"],
    prompts: [{ question: "First date idea...", answer: "Picnic at Crying Stone of Ilesi!" }],
    height: "165 cm",
    lifestyle: { smoking: "Non-smoker", drinking: "Non-drinker", pets: "All animals", religion: "Christian" },
  },

  // 6. NON-BINARY - BISEXUAL (Kenyatta University)
  {
    id: "sp-6",
    name: "Kai Adhiambo",
    age: 21,
    gender: "Non-binary",
    orientation: "Bisexual",
    campus: "Kenyatta University",
    course: "Environmental Studies & Botany",
    yearOfStudy: "3rd Year",
    distanceKm: 5,
    compatibilityScore: 89,
    verified: true,
    online: true,
    intentMode: "Dating",
    photos: [
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&auto=format&fit=crop&q=80",
    ],
    bio: "Eco-activist & botany student at KU. Passionate about climate change, analog photography, and thrift fashion.",
    interests: ["Volunteering", "Photography", "Philosophy", "Indie Rock"],
    prompts: [{ question: "World change goal...", answer: "Planting 10,000 indigenous trees on campus!" }],
    height: "173 cm",
    lifestyle: { smoking: "Non-smoker", drinking: "Social drinker", pets: "Cat lover", religion: "Spiritual" },
  },

  // 7. MALE - STRAIGHT (Egerton)
  {
    id: "sp-7",
    name: "Kevin Wafula",
    age: 23,
    gender: "Male",
    orientation: "Straight",
    campus: "Egerton University",
    course: "Agricultural Economics",
    yearOfStudy: "4th Year",
    distanceKm: 12,
    compatibilityScore: 88,
    verified: true,
    online: false,
    intentMode: "Dating",
    photos: [
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80",
    ],
    bio: "Agribusiness major & Rugby captain at Njoro campus! Looking for someone who loves outdoor adventures and good food.",
    interests: ["Basketball", "Baking & Cooking", "Travel & Backpacking", "Podcasts"],
    prompts: [{ question: "Secret talent...", answer: "I make the best smoked BBQ on campus!" }],
    height: "188 cm",
    lifestyle: { smoking: "Non-smoker", drinking: "Social drinker", pets: "Dog lover", religion: "Christian" },
  },

  // 8. FEMALE - STRAIGHT (Stanford)
  {
    id: "sp-8",
    name: "Sarah Jenkins",
    age: 21,
    gender: "Female",
    orientation: "Straight",
    campus: "Stanford University",
    course: "Computer Science & AI",
    yearOfStudy: "3rd Year",
    distanceKm: 1,
    compatibilityScore: 98,
    verified: true,
    online: true,
    intentMode: "Dating",
    photos: [
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80",
    ],
    bio: "AI researcher building generative models. Big fan of late-night espresso, indie rock concerts, and weekend bouldering!",
    interests: ["AI & Coding", "Indie Rock", "Gym & Fitness", "Coffee & Cafes"],
    prompts: [{ question: "Ideal Sunday...", answer: "Espresso at student union, 2 hours coding, acoustic guitar on oval lawn!" }],
    height: "168 cm",
    lifestyle: { smoking: "Non-smoker", drinking: "Social drinker", pets: "Dog lover", religion: "Agnostic" },
  },

  // 9. MALE - STRAIGHT (Harvard)
  {
    id: "sp-9",
    name: "Marcus Vance",
    age: 22,
    gender: "Male",
    orientation: "Straight",
    campus: "Harvard University",
    course: "Economics & Government",
    yearOfStudy: "4th Year",
    distanceKm: 15,
    compatibilityScore: 96,
    verified: true,
    online: true,
    intentMode: "Dating",
    photos: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80",
    ],
    bio: "Senior studying macroeconomics & international relations. Debate team captain, marathon runner, and chess enthusiast.",
    interests: ["Chess", "Philosophy", "Gym & Fitness", "Podcasts"],
    prompts: [{ question: "Challenge me to...", answer: "A 5-minute blitz chess game!" }],
    height: "182 cm",
    lifestyle: { smoking: "Non-smoker", drinking: "Social drinker", pets: "No pets", religion: "Christian" },
  },

  // 10. FEMALE - LESBIAN (Oxford)
  {
    id: "sp-10",
    name: "Eleanor Vance",
    age: 21,
    gender: "Female",
    orientation: "Lesbian",
    campus: "University of Oxford",
    course: "Literature & Classics",
    yearOfStudy: "3rd Year",
    distanceKm: 20,
    compatibilityScore: 93,
    verified: true,
    online: false,
    intentMode: "Dating",
    photos: [
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&auto=format&fit=crop&q=80",
    ],
    bio: "Classics major reading ancient Greek epics. Passionate about antique bookstores, tea rooms, and romantic poetry.",
    interests: ["Philosophy", "Coffee & Cafes", "Indie Rock", "Volunteering"],
    prompts: [{ question: "Favorite spot...", answer: "The Bodleian Library reading room." }],
    height: "171 cm",
    lifestyle: { smoking: "Non-smoker", drinking: "Social drinker", pets: "Cat lover", religion: "Agnostic" },
  },

  // 11. MALE - GAY (Harvard)
  {
    id: "sp-11",
    name: "Julian Rivera",
    age: 20,
    gender: "Male",
    orientation: "Gay",
    campus: "Harvard University",
    course: "Applied Mathematics",
    yearOfStudy: "2nd Year",
    distanceKm: 16,
    compatibilityScore: 90,
    verified: true,
    online: true,
    intentMode: "Dating",
    photos: [
      "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80",
    ],
    bio: "Math & CS major. Love classical piano, ML research, and finding quiet coffee shops in Boston.",
    interests: ["AI & Coding", "Philosophy", "Coffee & Cafes", "Chess"],
    prompts: [{ question: "Way to win me over...", answer: "Play Chopin on the piano or talk about quantum computing." }],
    height: "179 cm",
    lifestyle: { smoking: "Non-smoker", drinking: "Non-drinker", pets: "No pets", religion: "Agnostic" },
  },

  // 12. FEMALE - STRAIGHT (JKUAT)
  {
    id: "sp-12",
    name: "Sharon Kiprop",
    age: 21,
    gender: "Female",
    orientation: "Straight",
    campus: "Jomo Kenyatta University of Agriculture and Technology",
    course: "Architecture",
    yearOfStudy: "3rd Year",
    distanceKm: 6,
    compatibilityScore: 92,
    verified: true,
    online: true,
    intentMode: "Dating",
    photos: [
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80",
    ],
    bio: "Architecture student at JKUAT! 3D modeling by day, painter & foodie by night. Looking for a genuine partner.",
    interests: ["Photography", "Baking & Cooking", "Travel & Backpacking", "Indie Rock"],
    prompts: [{ question: "Must-have trait...", answer: "Sense of humor & passion for your major." }],
    height: "167 cm",
    lifestyle: { smoking: "Non-smoker", drinking: "Social drinker", pets: "Cat lover", religion: "Christian" },
  },

  // 13. MALE - STRAIGHT (UoN)
  {
    id: "sp-13",
    name: "Dennis Otieno",
    age: 22,
    gender: "Male",
    orientation: "Straight",
    campus: "University of Nairobi",
    course: "Civil Engineering",
    yearOfStudy: "4th Year",
    distanceKm: 3,
    compatibilityScore: 89,
    verified: true,
    online: true,
    intentMode: "Dating",
    photos: [
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80",
    ],
    bio: "Engineering senior & campus rugby player. Love road trips, acoustic music, and good food!",
    interests: ["Basketball", "Gym & Fitness", "Travel & Backpacking", "Hackathons"],
    prompts: [{ question: "Weekend routine...", answer: "Early morning jog, rugby practice, then nyama choma with friends." }],
    height: "186 cm",
    lifestyle: { smoking: "Non-smoker", drinking: "Social drinker", pets: "Dog lover", religion: "Christian" },
  },

  // 14. FEMALE - BISEXUAL (Strathmore)
  {
    id: "sp-14",
    name: "Chloe Nanjala",
    age: 20,
    gender: "Female",
    orientation: "Bisexual",
    campus: "Strathmore University",
    course: "Business Information Technology",
    yearOfStudy: "2nd Year",
    distanceKm: 4,
    compatibilityScore: 95,
    verified: true,
    online: true,
    intentMode: "Dating",
    photos: [
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&auto=format&fit=crop&q=80",
    ],
    bio: "Strathmore student interested in fintech startups & UI design. Bisexual & proud. Looking for genuine student connections!",
    interests: ["AI & Coding", "Crypto & Web3", "Coffee & Cafes", "Podcasts"],
    prompts: [{ question: "Unpopular opinion...", answer: "Pineapple on pizza is actually top tier." }],
    height: "169 cm",
    lifestyle: { smoking: "Non-smoker", drinking: "Social drinker", pets: "All animals", religion: "Spiritual" },
  },

  // 15. MALE - STRAIGHT (Kenyatta University)
  {
    id: "sp-15",
    name: "Victor Mwangi",
    age: 23,
    gender: "Male",
    orientation: "Straight",
    campus: "Kenyatta University",
    course: "Sports Science & Physical Education",
    yearOfStudy: "4th Year",
    distanceKm: 7,
    compatibilityScore: 87,
    verified: true,
    online: true,
    intentMode: "Dating",
    photos: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800&auto=format&fit=crop&q=80",
    ],
    bio: "KU athlete & personal trainer. Love track & field, healthy cooking, and swimming at the campus pool.",
    interests: ["Gym & Fitness", "Basketball", "Baking & Cooking", "Volunteering"],
    prompts: [{ question: "My goal...", answer: "Coaching Kenya's next Olympic sprint champion!" }],
    height: "183 cm",
    lifestyle: { smoking: "Non-smoker", drinking: "Non-drinker", pets: "Dog lover", religion: "Christian" },
  },

  // 16. FEMALE - STRAIGHT (Egerton)
  {
    id: "sp-16",
    name: "Faith Chebet",
    age: 21,
    gender: "Female",
    orientation: "Straight",
    campus: "Egerton University",
    course: "Veterinary Medicine",
    yearOfStudy: "3rd Year",
    distanceKm: 11,
    compatibilityScore: 90,
    verified: true,
    online: true,
    intentMode: "Dating",
    photos: [
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&auto=format&fit=crop&q=80",
    ],
    bio: "Future vet doctor at Egerton Njoro campus! Animal lover, horseback rider, and outdoor campfire enthusiast.",
    interests: ["Volunteering", "Travel & Backpacking", "Sci-Fi Movies", "Coffee & Cafes"],
    prompts: [{ question: "Quickest way to my heart...", answer: "Be kind to animals." }],
    height: "166 cm",
    lifestyle: { smoking: "Non-smoker", drinking: "Social drinker", pets: "All animals", religion: "Christian" },
  },

  // 17. MALE - GAY (Strathmore)
  {
    id: "sp-17",
    name: "Ethan Thorne",
    age: 21,
    gender: "Male",
    orientation: "Gay",
    campus: "Strathmore University",
    course: "Informatics & Computer Science",
    yearOfStudy: "3rd Year",
    distanceKm: 4,
    compatibilityScore: 91,
    verified: true,
    online: true,
    intentMode: "Dating",
    photos: [
      "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80",
    ],
    bio: "Software engineering student & indie game developer. Looking for a genuine guy for coffee dates and coding sessions.",
    interests: ["AI & Coding", "Gaming & Esports", "Indie Rock", "Anime"],
    prompts: [{ question: "Building right now...", answer: "An indie 2D RPG game!" }],
    height: "178 cm",
    lifestyle: { smoking: "Non-smoker", drinking: "Social drinker", pets: "Cat lover", religion: "Agnostic" },
  },

  // 18. FEMALE - STRAIGHT (UoN)
  {
    id: "sp-18",
    name: "Brenda Akoth",
    age: 22,
    gender: "Female",
    orientation: "Straight",
    campus: "University of Nairobi",
    course: "Law",
    yearOfStudy: "4th Year",
    distanceKm: 2,
    compatibilityScore: 94,
    verified: true,
    online: true,
    intentMode: "Dating",
    photos: [
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80",
    ],
    bio: "Parklands Law campus student! Moot court debater, human rights advocate, and jazz music lover.",
    interests: ["Debating", "Philosophy", "Live Music & Concerts", "Volunteering"],
    prompts: [{ question: "Dream date...", answer: "Live jazz at a rooftop lounge in Nairobi." }],
    height: "172 cm",
    lifestyle: { smoking: "Non-smoker", drinking: "Social drinker", pets: "No pets", religion: "Christian" },
  },

  // 19. MALE - BISEXUAL (JKUAT)
  {
    id: "sp-19",
    name: "Samuel Ndung'u",
    age: 22,
    gender: "Male",
    orientation: "Bisexual",
    campus: "Jomo Kenyatta University of Agriculture and Technology",
    course: "Biotechnology",
    yearOfStudy: "3rd Year",
    distanceKm: 7,
    compatibilityScore: 89,
    verified: true,
    online: true,
    intentMode: "Dating",
    photos: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80",
    ],
    bio: "Biotech researcher at Juja campus! Open-minded, bisexual, lover of genetics, swimming, and electronic music.",
    interests: ["Hackathons", "Gym & Fitness", "Indie Rock", "Sci-Fi Movies"],
    prompts: [{ question: "Life motto...", answer: "Curiosity above all else." }],
    height: "181 cm",
    lifestyle: { smoking: "Non-smoker", drinking: "Social drinker", pets: "Dog lover", religion: "Agnostic" },
  },

  // 20. FEMALE - STRAIGHT (MMUST)
  {
    id: "sp-20",
    name: "Mercy Juma",
    age: 21,
    gender: "Female",
    orientation: "Straight",
    campus: "Masinde Muliro University of Science and Technology",
    course: "Mechanical Engineering",
    yearOfStudy: "3rd Year",
    distanceKm: 8,
    compatibilityScore: 93,
    verified: true,
    online: true,
    intentMode: "Dating",
    photos: [
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80",
    ],
    bio: "Mechanical engineering girl at MMUST! CAD designer, Formula 1 fan, and weekend baker.",
    interests: ["Hackathons", "Baking & Cooking", "Gym & Fitness", "Basketball"],
    prompts: [{ question: "Favorite sport...", answer: "Formula 1 & Campus Basketball!" }],
    height: "168 cm",
    lifestyle: { smoking: "Non-smoker", drinking: "Non-drinker", pets: "Cat lover", religion: "Christian" },
  },
];
