export interface Institution {
  id: string;
  name: string;
  shortName: string;
  country: string;
  stateCounty: string;
  type: "University" | "College" | "Polytechnic" | "Technical Institute";
  domains: string[];
  logoUrl: string;
  bannerUrl: string;
  location: string;
  verifiedStudentsCount: number;
  activeUsersCount: number;
  clubsCount: number;
  establishedYear: number;
  popularMajors: string[];
}

export const COUNTRIES = [
  "Kenya",
  "United States",
  "United Kingdom",
  "Canada",
  "South Africa",
  "Nigeria",
];

export const INSTITUTIONS_DATA: Institution[] = [
  // KENYA INSTITUTIONS
  {
    id: "uon",
    name: "University of Nairobi",
    shortName: "UoN",
    country: "Kenya",
    stateCounty: "Nairobi",
    type: "University",
    domains: ["uonbi.ac.ke", "students.uonbi.ac.ke"],
    logoUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=1200&auto=format&fit=crop&q=80",
    location: "Nairobi CBD, Kenya",
    verifiedStudentsCount: 14250,
    activeUsersCount: 8420,
    clubsCount: 42,
    establishedYear: 1956,
    popularMajors: ["Medicine & Surgery", "Law", "Computer Science", "Civil Engineering", "Business Administration"],
  },
  {
    id: "jkuat",
    name: "Jomo Kenyatta University of Agriculture and Technology",
    shortName: "JKUAT",
    country: "Kenya",
    stateCounty: "Kiambu",
    type: "University",
    domains: ["jkuat.ac.ke", "students.jkuat.ac.ke"],
    logoUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&auto=format&fit=crop&q=80",
    location: "Juja, Kiambu, Kenya",
    verifiedStudentsCount: 12890,
    activeUsersCount: 7150,
    clubsCount: 38,
    establishedYear: 1994,
    popularMajors: ["Mechatronics Engineering", "Software Engineering", "Architecture", "Biotechnology"],
  },
  {
    id: "ku",
    name: "Kenyatta University",
    shortName: "KU",
    country: "Kenya",
    stateCounty: "Nairobi",
    type: "University",
    domains: ["ku.ac.ke", "students.ku.ac.ke"],
    logoUrl: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&auto=format&fit=crop&q=80",
    location: "Thika Road, Nairobi, Kenya",
    verifiedStudentsCount: 15400,
    activeUsersCount: 9100,
    clubsCount: 45,
    establishedYear: 1985,
    popularMajors: ["Education", "Performing Arts", "Environmental Studies", "Sports Science"],
  },
  {
    id: "mmust",
    name: "Masinde Muliro University of Science and Technology",
    shortName: "MMUST",
    country: "Kenya",
    stateCounty: "Kakamega",
    type: "University",
    domains: ["mmust.ac.ke", "student.mmust.ac.ke"],
    logoUrl: "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=1200&auto=format&fit=crop&q=80",
    location: "Kakamega Town, Kenya",
    verifiedStudentsCount: 9400,
    activeUsersCount: 5200,
    clubsCount: 29,
    establishedYear: 2007,
    popularMajors: ["Disaster Management", "Mechanical Engineering", "Nursing", "Criminology"],
  },
  {
    id: "strathmore",
    name: "Strathmore University",
    shortName: "Strathmore",
    country: "Kenya",
    stateCounty: "Nairobi",
    type: "University",
    domains: ["strathmore.edu"],
    logoUrl: "https://images.unsplash.com/photo-1548625361-18658097f480?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&auto=format&fit=crop&q=80",
    location: "Madaraka, Nairobi, Kenya",
    verifiedStudentsCount: 6800,
    activeUsersCount: 4300,
    clubsCount: 24,
    establishedYear: 1961,
    popularMajors: ["Financial Economics", "Informatics & Computer Science", "Law", "Business Information Technology"],
  },
  {
    id: "egerton",
    name: "Egerton University",
    shortName: "Egerton",
    country: "Kenya",
    stateCounty: "Nakuru",
    type: "University",
    domains: ["egerton.ac.ke"],
    logoUrl: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=1200&auto=format&fit=crop&q=80",
    location: "Njoro, Nakuru, Kenya",
    verifiedStudentsCount: 11200,
    activeUsersCount: 6300,
    clubsCount: 31,
    establishedYear: 1939,
    popularMajors: ["Agricultural Economics", "Veterinary Medicine", "Food Science", "Botany"],
  },

  // GLOBAL INSTITUTIONS
  {
    id: "stanford",
    name: "Stanford University",
    shortName: "Stanford",
    country: "United States",
    stateCounty: "California",
    type: "University",
    domains: ["stanford.edu"],
    logoUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&auto=format&fit=crop&q=80",
    location: "Stanford, California, USA",
    verifiedStudentsCount: 17200,
    activeUsersCount: 11400,
    clubsCount: 85,
    establishedYear: 1885,
    popularMajors: ["Computer Science", "Symbolic Systems", "Economics", "Human Biology"],
  },
  {
    id: "harvard",
    name: "Harvard University",
    shortName: "Harvard",
    country: "United States",
    stateCounty: "Massachusetts",
    type: "University",
    domains: ["harvard.edu"],
    logoUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&auto=format&fit=crop&q=80",
    location: "Cambridge, Massachusetts, USA",
    verifiedStudentsCount: 22000,
    activeUsersCount: 14200,
    clubsCount: 95,
    establishedYear: 1636,
    popularMajors: ["Government", "Economics", "Applied Mathematics", "History"],
  },
  {
    id: "oxford",
    name: "University of Oxford",
    shortName: "Oxford",
    country: "United Kingdom",
    stateCounty: "Oxfordshire",
    type: "University",
    domains: ["ox.ac.uk"],
    logoUrl: "https://images.unsplash.com/photo-1548625361-18658097f480?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&auto=format&fit=crop&q=80",
    location: "Oxford, United Kingdom",
    verifiedStudentsCount: 24500,
    activeUsersCount: 16100,
    clubsCount: 110,
    establishedYear: 1096,
    popularMajors: ["Philosophy, Politics & Economics (PPE)", "Law", "Classics", "Physics"],
  },
];
