export interface Institution {
  id: string;
  name: string;
  shortName: string;
  country: string;
  city: string;
  stateCounty: string;
  type: "University" | "College" | "Polytechnic" | "Technical Institute";
  domains: string[];
  logoUrl: string;
  bannerUrl: string;
  location: string;
  verifiedStudentsCount: number;
  activeUsersCount: number;
  clubsCount: number;
  establishedYear: number;
  popularMajors: string[];
}

export interface CountryOption {
  code: string;
  name: string;
  flag: string;
  region: "East Africa" | "Central Africa" | "Horn of Africa" | "Global";
  active: boolean;
}

export const SUPPORTED_COUNTRIES: CountryOption[] = [
  { code: "KE", name: "Kenya", flag: "🇰🇪", region: "East Africa", active: true },
  { code: "UG", name: "Uganda", flag: "🇺🇬", region: "East Africa", active: true },
  { code: "TZ", name: "Tanzania", flag: "🇹🇿", region: "East Africa", active: true },
  { code: "RW", name: "Rwanda", flag: "🇷🇼", region: "East Africa", active: true },
  { code: "BI", name: "Burundi", flag: "🇧🇮", region: "East Africa", active: true },
  { code: "SS", name: "South Sudan", flag: "🇸🇸", region: "East Africa", active: true },
  { code: "ET", name: "Ethiopia", flag: "🇪🇹", region: "Horn of Africa", active: true },
  { code: "CD", name: "DR Congo", flag: "🇨🇩", region: "Central Africa", active: true },
  { code: "US", name: "United States", flag: "🇺🇸", region: "Global", active: true },
  { code: "UK", name: "United Kingdom", flag: "🇬🇧", region: "Global", active: true },
  { code: "ZA", name: "South Africa", flag: "🇿🇦", region: "Global", active: true },
];

export const COUNTRIES = SUPPORTED_COUNTRIES.map((c) => c.name);

export const INSTITUTIONS_DATA: Institution[] = [
  // ================= KENYA 🇰🇪 =================
  {
    id: "uon",
    name: "University of Nairobi",
    shortName: "UoN",
    country: "Kenya",
    city: "Nairobi",
    stateCounty: "Nairobi",
    type: "University",
    domains: ["uonbi.ac.ke", "students.uonbi.ac.ke"],
    logoUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=1200&auto=format&fit=crop&q=80",
    location: "Nairobi CBD, Kenya",
    verifiedStudentsCount: 14250,
    activeUsersCount: 8420,
    clubsCount: 42,
    establishedYear: 1956,
    popularMajors: ["Medicine & Surgery", "Law", "Computer Science", "Civil Engineering", "Business Administration"],
  },
  {
    id: "jkuat",
    name: "Jomo Kenyatta University of Agriculture and Technology",
    shortName: "JKUAT",
    country: "Kenya",
    city: "Juja",
    stateCounty: "Kiambu",
    type: "University",
    domains: ["jkuat.ac.ke", "students.jkuat.ac.ke"],
    logoUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&auto=format&fit=crop&q=80",
    location: "Juja, Kiambu, Kenya",
    verifiedStudentsCount: 12890,
    activeUsersCount: 7150,
    clubsCount: 38,
    establishedYear: 1994,
    popularMajors: ["Mechatronics Engineering", "Software Engineering", "Architecture", "Biotechnology"],
  },
  {
    id: "ku",
    name: "Kenyatta University",
    shortName: "KU",
    country: "Kenya",
    city: "Nairobi",
    stateCounty: "Nairobi",
    type: "University",
    domains: ["ku.ac.ke", "students.ku.ac.ke"],
    logoUrl: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&auto=format&fit=crop&q=80",
    location: "Thika Road, Nairobi, Kenya",
    verifiedStudentsCount: 15400,
    activeUsersCount: 9100,
    clubsCount: 45,
    establishedYear: 1985,
    popularMajors: ["Education", "Performing Arts", "Environmental Studies", "Sports Science"],
  },
  {
    id: "mmust",
    name: "Masinde Muliro University of Science and Technology",
    shortName: "MMUST",
    country: "Kenya",
    city: "Kakamega",
    stateCounty: "Kakamega",
    type: "University",
    domains: ["mmust.ac.ke", "student.mmust.ac.ke"],
    logoUrl: "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=1200&auto=format&fit=crop&q=80",
    location: "Kakamega Town, Kenya",
    verifiedStudentsCount: 9400,
    activeUsersCount: 5200,
    clubsCount: 29,
    establishedYear: 2007,
    popularMajors: ["Disaster Management", "Mechanical Engineering", "Nursing", "Criminology"],
  },
  {
    id: "strathmore",
    name: "Strathmore University",
    shortName: "Strathmore",
    country: "Kenya",
    city: "Nairobi",
    stateCounty: "Nairobi",
    type: "University",
    domains: ["strathmore.edu"],
    logoUrl: "https://images.unsplash.com/photo-1548625361-18658097f480?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&auto=format&fit=crop&q=80",
    location: "Madaraka, Nairobi, Kenya",
    verifiedStudentsCount: 6800,
    activeUsersCount: 4300,
    clubsCount: 24,
    establishedYear: 1961,
    popularMajors: ["Financial Economics", "Informatics & Computer Science", "Law", "Business Information Technology"],
  },
  {
    id: "moi",
    name: "Moi University",
    shortName: "Moi",
    country: "Kenya",
    city: "Eldoret",
    stateCounty: "Uasin Gishu",
    type: "University",
    domains: ["mu.ac.ke"],
    logoUrl: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=1200&auto=format&fit=crop&q=80",
    location: "Kesses, Eldoret, Kenya",
    verifiedStudentsCount: 11800,
    activeUsersCount: 6900,
    clubsCount: 35,
    establishedYear: 1984,
    popularMajors: ["Aerospace Engineering", "Media Studies", "Medicine", "Public Health"],
  },

  // ================= UGANDA 🇺🇬 =================
  {
    id: "makerere",
    name: "Makerere University",
    shortName: "Makerere",
    country: "Uganda",
    city: "Kampala",
    stateCounty: "Central",
    type: "University",
    domains: ["mak.ac.ug"],
    logoUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&auto=format&fit=crop&q=80",
    location: "Makerere Hill, Kampala, Uganda",
    verifiedStudentsCount: 16500,
    activeUsersCount: 9800,
    clubsCount: 50,
    establishedYear: 1922,
    popularMajors: ["Software Engineering", "Human Medicine", "Mass Communication", "Agriculture", "Economics"],
  },
  {
    id: "must_ug",
    name: "Mbarara University of Science and Technology",
    shortName: "MUST",
    country: "Uganda",
    city: "Mbarara",
    stateCounty: "Western",
    type: "University",
    domains: ["must.ac.ug"],
    logoUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=1200&auto=format&fit=crop&q=80",
    location: "Mbarara Town, Uganda",
    verifiedStudentsCount: 7400,
    activeUsersCount: 4600,
    clubsCount: 22,
    establishedYear: 1989,
    popularMajors: ["Biomedical Engineering", "Pharmacy", "Computer Science", "Development Studies"],
  },
  {
    id: "kiu",
    name: "Kampala International University",
    shortName: "KIU",
    country: "Uganda",
    city: "Kampala",
    stateCounty: "Kansanga",
    type: "University",
    domains: ["kiu.ac.ug"],
    logoUrl: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=1200&auto=format&fit=crop&q=80",
    location: "Kansanga, Kampala, Uganda",
    verifiedStudentsCount: 11200,
    activeUsersCount: 6800,
    clubsCount: 30,
    establishedYear: 2001,
    popularMajors: ["Clinical Medicine", "International Relations", "Business Computing", "Nursing"],
  },

  // ================= TANZANIA 🇹🇿 =================
  {
    id: "udsm",
    name: "University of Dar es Salaam",
    shortName: "UDSM",
    country: "Tanzania",
    city: "Dar es Salaam",
    stateCounty: "Dar es Salaam",
    type: "University",
    domains: ["udsm.ac.tz"],
    logoUrl: "https://images.unsplash.com/photo-1548625361-18658097f480?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&auto=format&fit=crop&q=80",
    location: "Mlimani Campus, Dar es Salaam, Tanzania",
    verifiedStudentsCount: 15800,
    activeUsersCount: 9400,
    clubsCount: 48,
    establishedYear: 1961,
    popularMajors: ["Telecommunication Engineering", "Law", "Geology", "Fine Arts", "Economics"],
  },
  {
    id: "udom",
    name: "University of Dodoma",
    shortName: "UDOM",
    country: "Tanzania",
    city: "Dodoma",
    stateCounty: "Dodoma",
    type: "University",
    domains: ["udom.ac.tz"],
    logoUrl: "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&auto=format&fit=crop&q=80",
    location: "Dodoma Capital, Tanzania",
    verifiedStudentsCount: 13200,
    activeUsersCount: 7800,
    clubsCount: 36,
    establishedYear: 2007,
    popularMajors: ["Mining Engineering", "Cybersecurity", "Health Sciences", "Education"],
  },

  // ================= RWANDA 🇷🇼 =================
  {
    id: "ur",
    name: "University of Rwanda",
    shortName: "UR",
    country: "Rwanda",
    city: "Kigali",
    stateCounty: "Kigali",
    type: "University",
    domains: ["ur.ac.rw"],
    logoUrl: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=1200&auto=format&fit=crop&q=80",
    location: "Gikondo, Kigali, Rwanda",
    verifiedStudentsCount: 12100,
    activeUsersCount: 7300,
    clubsCount: 34,
    establishedYear: 2013,
    popularMajors: ["Information Technology", "Renewable Energy", "Architecture", "Medicine"],
  },
  {
    id: "cmu_africa",
    name: "Carnegie Mellon University Africa",
    shortName: "CMU-Africa",
    country: "Rwanda",
    city: "Kigali",
    stateCounty: "Kigali Innovation City",
    type: "University",
    domains: ["africa.engineering.cmu.edu"],
    logoUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&auto=format&fit=crop&q=80",
    location: "Kigali Innovation City, Rwanda",
    verifiedStudentsCount: 1400,
    activeUsersCount: 1100,
    clubsCount: 15,
    establishedYear: 2011,
    popularMajors: ["MS in Information Technology", "MS in Electrical & Computer Engineering"],
  },

  // ================= BURUNDI 🇧🇮 =================
  {
    id: "ub",
    name: "University of Burundi",
    shortName: "UB",
    country: "Burundi",
    city: "Bujumbura",
    stateCounty: "Bujumbura Mairie",
    type: "University",
    domains: ["ub.edu.bi"],
    logoUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=1200&auto=format&fit=crop&q=80",
    location: "Mutanga, Bujumbura, Burundi",
    verifiedStudentsCount: 6500,
    activeUsersCount: 3900,
    clubsCount: 18,
    establishedYear: 1964,
    popularMajors: ["Agronomy", "Economics", "Law", "Computer Engineering"],
  },

  // ================= SOUTH SUDAN 🇸🇸 =================
  {
    id: "juba_uni",
    name: "University of Juba",
    shortName: "UJ",
    country: "South Sudan",
    city: "Juba",
    stateCounty: "Central Equatoria",
    type: "University",
    domains: ["juba.edu.ss"],
    logoUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&auto=format&fit=crop&q=80",
    location: "Juba, South Sudan",
    verifiedStudentsCount: 5800,
    activeUsersCount: 3200,
    clubsCount: 16,
    establishedYear: 1975,
    popularMajors: ["Petroleum Geology", "Peace & Conflict Resolution", "Medicine", "Public Administration"],
  },

  // ================= GLOBAL (USA & UK) 🇺🇸 🇬🇧 =================
  {
    id: "stanford",
    name: "Stanford University",
    shortName: "Stanford",
    country: "United States",
    city: "Stanford",
    stateCounty: "California",
    type: "University",
    domains: ["stanford.edu"],
    logoUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&auto=format&fit=crop&q=80",
    location: "Stanford, California, USA",
    verifiedStudentsCount: 17200,
    activeUsersCount: 11400,
    clubsCount: 85,
    establishedYear: 1885,
    popularMajors: ["Computer Science", "Symbolic Systems", "Economics", "Human Biology"],
  },
  {
    id: "oxford",
    name: "University of Oxford",
    shortName: "Oxford",
    country: "United Kingdom",
    city: "Oxford",
    stateCounty: "Oxfordshire",
    type: "University",
    domains: ["ox.ac.uk"],
    logoUrl: "https://images.unsplash.com/photo-1548625361-18658097f480?w=200&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&auto=format&fit=crop&q=80",
    location: "Oxford, United Kingdom",
    verifiedStudentsCount: 24500,
    activeUsersCount: 16100,
    clubsCount: 110,
    establishedYear: 1096,
    popularMajors: ["Philosophy, Politics & Economics (PPE)", "Law", "Classics", "Physics"],
  },
];
